[package]
name = "derpy"
version = "0.1.0"
authors = ["Oliver Maskery <omaskery@googlemail.com>"]

[dependencies]
clap = "2.31.2"
serde = "1.0.43"
serde_derive = "1.0.43"
serde_json = "1.0.16"
failure = "0.1.1"
failure_derive = "0.1.1"
